app/urls.py
from django.contrib import admin
from django.urls import path
from .cart_views import (
    add_to_card,
    remove_from_card,
    add_to_card_summary,
    remove_single_item_from_card,
    remove_all_item_from_card,
    )
from .views import (
	HomeView,
	ItemDetailView,
    OrderSummary,  
    Checkout,
    
    PaymentView,
    add_coupon,
    RequestRefundView,
    ContactView,
    CategoryDetailView,
    OrderedItems,
    OrderStatus,
    RequestRefundedView
    )

from . import apis
from django.views.generic import TemplateView

app_name = 'app'
urlpatterns = [
    # path('', views.home,name='home'),
    path('',HomeView.as_view(),name='home'),   
    path('product/<slug>',ItemDetailView.as_view(),name='product'),
    path('add-to-card/<slug>',add_to_card,name='add-to-card'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('add-to-card-summary/<slug>',add_to_card_summary,name='add-to-card-summary'),
    path('order-summary/',OrderSummary.as_view(),name='order-summary'),
    path('remove-from-card/<slug>',remove_from_card,name='remove-from-card'),
    path('remove-all-from-card/<slug>',remove_all_item_from_card,name='remove-all-from-card'),
    path('checkout/',Checkout.as_view(),name='checkout'),
    path('add-coupon/',add_coupon, name='add-coupon'),
    path('remove-single/<slug>/',remove_single_item_from_card,name='remove-single-element'),
    path('payment/<payment_option>',PaymentView.as_view(),name = 'payment'),
    path('request-refund/<id>/',RequestRefundView.as_view(),name = 'request-refund'),
    path('request-refunded/<id>', RequestRefundedView.as_view(), name='request-refunded'),
    path('category/<id>/<slug>/', CategoryDetailView.as_view(), name='category'),
    path('ordered/items/', OrderedItems.as_view(), name='ordered-items'),
    path('order-status/<id>/', OrderStatus.as_view(), name='order-status'),



    # APIS
    path('api/category/', apis.CategoryViewSet.as_view()),
    path('api/category/<pk>/', apis.CategoryDetailViewSet.as_view({
        'get':'retrieve', 
        'delete' : 'destroy',
        'put' : 'update'
    })),
   
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/', include('allauth.urls')),
    # path('auth/', include('rest_framework_social_oauth2.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/templates/base.html
{% load static %}
{% load card_template_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}
    {% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Place favicon.ico in the root directory -->
    
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    

    <!-- All css files are included here. -->
    <!-- Bootstrap fremwork main css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Owl Carousel main css -->
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <!-- This core.css file contents all plugings css file. -->
    <link rel="stylesheet" href="{% static 'css/core.css' %}">
    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="{% static 'css/shortcode/shortcodes.css' %}">
    <!-- Theme main style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Responsive css -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- User style -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    {% block css_style %}
    {% endblock css_style %}
   
    <!-- Modernizr JS -->
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
 
</head>

<body>

  <div class="wrapper fixed__footer">

    {% include 'navbar.html' %}

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>
    <div class="body__overlay"></div>
    {% block category %}
    {% endblock category %}

    {% block content %}
    {% endblock content %}

    

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  



  </div>
  
  <script src="{% static 'js/vendor/jquery-1.12.0.min.js' %}"></script>
  <!-- Bootstrap framework js -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- All js plugins included in this file. -->
  <script src="{% static 'js/plugins.js' %}"></script>
  <script src="{% static 'js/slick.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <!-- Waypoints.min.js. -->
  <script src="{% static 'js/waypoints.min.js' %}"></script>
  <!-- Main js file that contents all jQuery plugins activation. -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

app/templates/brequest_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<main class="mt-5 pt-4">
  <div class="container">
    <form method="POST" id="stripe-form">
        {% csrf_token %}
        {{ form|crispy }}
      <button class="btn btn-primary">Submit</button>
    </form>
  </div>
</main>
{% endblock %}

app/templates/category.html
{% load mptt_tags %}
<section class="categories-slider-area bg__white">
  <div class="container">
      <div class="row">
          <!-- Start Left Feature -->
          <div class="col-md-9 col-lg-9 col-sm-8 col-xs-12 float-left-style">
              <!-- Start Slider Area -->
              <div class="slider__container slider--one">
                  <div class="slider__activation__wrap owl-carousel owl-theme">
                      <!-- Start Single Slide -->
                      <div class="slide slider__full--screen slider-height-inherit slider-text-right" style="background: rgba(0, 0, 0, 0) no-repeat scroll center center / cover ;">
                          <div class="container">
                              <div class="row">
                                  <div class="col-md-10 col-lg-8 col-md-offset-2 col-lg-offset-4 col-sm-12 col-xs-12">
                                      <div class="slider__inner">
                                          <h1>New Product <span class="text--theme">Collection</span></h1>
                                          <div class="slider__btn">
                                              <a class="htc__btn" href="/order-summary/">shop now</a>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <!-- End Single Slide -->
                      <!-- Start Single Slide -->
                      <div class="slide slider__full--screen slider-height-inherit  slider-text-left" style="background: rgba(0, 0, 0, 0) no-repeat scroll center center / cover ;">
                          <div class="container">
                              <div class="row">
                                  <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
                                      <div class="slider__inner">
                                          <h1>New Product <span class="text--theme">Collection</span></h1>
                                          <div class="slider__btn">
                                              <a class="htc__btn" href="cart.html">shop now</a>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <!-- End Single Slide -->
                  </div>
              </div>
              <!-- Start Slider Area -->
          </div>
          <div class="col-md-3 col-lg-3 col-sm-4 col-xs-12 float-right-style">
              <div class="categories-menu mrg-xs">
                  <div class="category-heading">
                      <h3> Browse Categories</h3>
                  </div>
                  <div class="category-menu-list">                             
                      <ul>
                        {% recursetree category %}                       
                          <li><a href="/category/{{ node.id }}/{{ node.slug }}/">{{ node.title }} {% if not node.is_leaf_node %}<i class="zmdi zmdi-chevron-right"></i>{% endif %}</a>
                              {% if not node.is_leaf_node %}
                              <div class="category-menu-dropdown">
                                  <div class="category-part-1 category-common mb--30">
                                  {% for child in node.get_children %}                                                                       
                                    <h4 class="categories-subtitle"><a href="/category/{{ child.id }}/{{ child.slug }}/"> {{child}} </a></h4> 
                                    {% if not child.is_leaf_node %}
                                        {% for leaf in child.get_children %}
                                            <ul class="children">
                                                <li><a href="/category/{{ leaf.id }}/{{ leaf.slug }}/"> {{ leaf }}</a></li>                                            
                                            </ul>
                                        {% endfor %}                                      
                                    {% endif %}
                                   {% endfor %}                                   
                                  </div>                                  
                              </div>
                              {% endif %}
                          </li>
                          {% endrecursetree %}
                      </ul>
                  </div>
              </div>
          </div>
          <!-- End Left Feature -->
      </div>
  </div>
</section>

app/templates/checkout-page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load card_template_tags %}
{% block title %}Check Out{% endblock %}
{% block content %}
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          
          <div class="card">
            {% comment %} <h3 style="font-family: sans-serif; margin: 10px;">Billing Address</h3> {% endcomment %}

            <!--Card content-->
          <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" onclick = "sameBilling()" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" onclick="functionShipping()" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                  <label for="billing_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" onclick = "defaultBilling()" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>
            {% comment %} <form method="POST" class="card-body">  
              {% csrf_token %}
              {{ billing_form|crispy }}
              <!-- <button class="btn btn-primary">CONTINUE TO CHECKOUT</button> -->
              <div id="shipping">
              <h3 style="font-family: sans-serif; margin: 10px;">Shipping Address</h3>
            
                {{ shipping_form|crispy }}
              
              </div>
            
              <button class="btn btn-primary">CONTINUE TO CHECKOUT</button>

              <!--address-->   
            </form> {% endcomment %}
          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ request.user|cart_item_count }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.item.title}} x {{ order_item.quantity }}</h6>
                <small class="text-muted">{{ order_item.item.description }}</small>
              </div>
              {% if order_item.item.discount_price %}
              <span class="text-muted">${{ order_item.item.discount_price }}</span>
              
              {% else %}
              <span class="text-muted">${{ order_item.item.price }}</span>
              {% endif %}
            </li>           
            {% endfor %}

            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-${{ order.total|multiply}}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{order.total}}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          
          <form class="card p-2" method="POST" action = "{% url 'app:add-coupon' %}">
            {% csrf_token %}
            {{ couponform.code }}
            <div class="input-group-append">
              <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
          </form>

          <!-- <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form> -->
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
     

    </div>
  </main>
  {% endblock %}
{% block extra_scripts %}
<script>
  
  var use_default_shipping = document.getElementById("use_default_shipping");
  var hideable_shipping_form = document.getElementsByClassName('hideable_shipping_form');
  var hideable_billing_form = document.getElementsByClassName('hideable_billing_form');
  var same_billing_address = document.getElementById("same_billing_address")
 
  function functionShipping(){
    
    if(document.getElementById("use_default_shipping").checked){
      hideable_shipping_form[0].hidden = true
    }
    else{
      hideable_shipping_form[0].hidden = false
    }
  }

  function defaultBilling(){
    if(document.getElementById("use_default_billing").checked){
      hideable_billing_form[0].hidden = true
    }
    else{
      hideable_billing_form[0].hidden = false
    }

  }
  
  function sameBilling(){
    if(same_billing_address.checked){
      hideable_billing_form[0].hidden = true
    }
    else{
      hideable_billing_form[0].hidden = false
    }

  }

  </script>
{% endblock extra_scripts %}
  

app/templates/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="ht__bradcaump__area" style="background: rgba(0, 0, 0, 0) url(images/bg/2.jpg) no-repeat scroll center center / cover ;">
    <div class="ht__bradcaump__wrap">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="bradcaump__inner text-center">
                        <h2 class="bradcaump-title">Contact US</h2>
                        <nav class="bradcaump-inner">
                            <a class="breadcrumb-item" href="index.html">Home</a>
                            <span class="brd-separetor">/</span>
                            <span class="breadcrumb-item active">Contact US</span>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- Start Contact Area -->
<section class="htc__contact__area ptb--120 bg__white">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                <div class="htc__contact__container">
                    <div class="htc__contact__address">
                        <h2 class="contact__title">contact info</h2>
                        <div class="contact__address__inner">
                            <!-- Start Single Adress -->
                            <div class="single__contact__address">
                                <div class="contact__icon">
                                    <span class="ti-location-pin"></span>
                                </div>
                                <div class="contact__details">
                                    <p>Location : <br> 77, seventh avenue, Brat road USA.</p>
                                </div>
                            </div>
                            <!-- End Single Adress -->
                        </div>
                        <div class="contact__address__inner">
                            <!-- Start Single Adress -->
                            <div class="single__contact__address">
                                <div class="contact__icon">
                                    <span class="ti-mobile"></span>
                                </div>
                                <div class="contact__details">
                                    <p> Phone : <br><a href="#">+012 345 678 102 </a></p>
                                </div>
                            </div>
                            <!-- End Single Adress -->
                            <!-- Start Single Adress -->
                            <div class="single__contact__address">
                                <div class="contact__icon">
                                    <span class="ti-email"></span>
                                </div>
                                <div class="contact__details">
                                    <p> Mail :<br><a href="#">info@example.com</a></p>
                                </div>
                            </div>
                            <!-- End Single Adress -->
                        </div>
                    </div>
                    <div class="contact-form-wrap">
                    <div class="contact-title">
                        <h2 class="contact__title">Get In Touch</h2>
                    </div>
                    <form id="contact-form" action="mail.php" method="post">
                        <div class="single-contact-form">
                            <div class="contact-box name">
                                <input type="text" name="name" placeholder="Your Nme*">
                                <input type="email" name="email" placeholder="Mail*">
                            </div>
                        </div>
                        <div class="single-contact-form">
                            <div class="contact-box subject">
                                <input type="text" name="subject" placeholder="Subject*">
                            </div>
                        </div>
                        <div class="single-contact-form">
                            <div class="contact-box message">
                                <textarea name="message"  placeholder="Massage*"></textarea>
                            </div>
                        </div>
                        <div class="contact-btn">
                            <button type="submit" class="fv-btn">SEND</button>
                        </div>
                    </form>
                </div> 
                <div class="form-output">
                    <p class="form-messege"></p>
                </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 smt-30 xmt-30">
                <div class="map-contacts">
                    <div id="googleMap"></div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}    

{% block extra_scripts %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBmGmeot5jcjdaJTvfCmQPfzeoG_pABeWo"></script>
<script>
    // When the window has finished loading create our google map below
    google.maps.event.addDomListener(window, 'load', init);

    function init() {
        // Basic options for a simple Google Map
        // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
        var mapOptions = {
            // How zoomed in you want the map to start at (always required)
            zoom: 12,

            scrollwheel: false,

            // The latitude and longitude to center the map (always required)
            center: new google.maps.LatLng(23.7286, 90.3854), // New York

            // How you would like to style the map. 
            // This is where you would paste any style found on Snazzy Maps.
                styles: [


{
    "featureType": "administrative",
    "elementType": "all",
    "stylers": [
        {
            "hue": "#ff0000"
        }
    ]
},
{
    "featureType": "administrative",
    "elementType": "geometry",
    "stylers": [
        {
            "color": "#888888"
        }
    ]
},
{
    "featureType": "administrative",
    "elementType": "geometry.fill",
    "stylers": [
        {
            "hue": "#ff0000"
        }
    ]
},
{
    "featureType": "administrative",
    "elementType": "labels.text",
    "stylers": [
        {
            "color": "#6e6e6e"
        },
        {
            "visibility": "simplified"
        }
    ]
},
{
    "featureType": "administrative.country",
    "elementType": "geometry",
    "stylers": [
        {
            "color": "#6f6b6b"
        }
    ]
},
{
    "featureType": "landscape",
    "elementType": "labels.text",
    "stylers": [
        {
            "color": "#c5c5c5"
        }
    ]
},
{
    "featureType": "landscape.natural",
    "elementType": "geometry",
    "stylers": [
        {
            "color": "#cfcfcf"
        }
    ]
},
{
    "featureType": "landscape.natural.landcover",
    "elementType": "all",
    "stylers": [
        {
            "hue": "#ff0000"
        }
    ]
},
{
    "featureType": "landscape.natural.landcover",
    "elementType": "geometry",
    "stylers": [
        {
            "hue": "#ff0000"
        }
    ]
},
{
    "featureType": "poi",
    "elementType": "all",
    "stylers": [
        {
            "visibility": "off"
        }
    ]
},
{
    "featureType": "poi",
    "elementType": "labels.text",
    "stylers": [
        {
            "visibility": "off"
        },
        {
            "color": "#909090"
        }
    ]
},
{
    "featureType": "poi",
    "elementType": "labels.icon",
    "stylers": [
        {
            "visibility": "off"
        }
    ]
},
{
    "featureType": "poi.medical",
    "elementType": "geometry",
    "stylers": [
        {
            "color": "#e5e5e5"
        }
    ]
},
{
    "featureType": "poi.park",
    "elementType": "geometry",
    "stylers": [
        {
            "color": "#e5e5e5"
        }
    ]
},
{
    "featureType": "poi.place_of_worship",
    "elementType": "geometry",
    "stylers": [
        {
            "color": "#ff0000"
        }
    ]
},
{
    "featureType": "poi.sports_complex",
    "elementType": "geometry",
    "stylers": [
        {
            "color": "#f7f7f7"
        }
    ]
},
{
    "featureType": "road",
    "elementType": "geometry.fill",
    "stylers": [
        {
            "color": "#ffffff"
        }
    ]
},
{
    "featureType": "road",
    "elementType": "geometry.stroke",
    "stylers": [
        {
            "gamma": 7.18
        }
    ]
},
{
    "featureType": "road",
    "elementType": "labels.icon",
    "stylers": [
        {
            "visibility": "off"
        }
    ]
},
{
    "featureType": "road.local",
    "elementType": "labels.text",
    "stylers": [
        {
            "visibility": "simplified"
        }
    ]
},
{
    "featureType": "transit.line",
    "elementType": "geometry",
    "stylers": [
        {
            "gamma": 0.48
        }
    ]
},
{
    "featureType": "transit.station",
    "elementType": "labels.icon",
    "stylers": [
        {
            "visibility": "off"
        }
    ]
},
{
    "featureType": "water",
    "elementType": "all",
    "stylers": [
        {
            "color": "#bcbcbc"
        },
        {
            "visibility": "on"
        }
    ]
},
{
    "featureType": "water",
    "elementType": "labels.text.fill",
    "stylers": [
        {
            "color": "#ffffff"
        }
    ]
}
]
        };

        // Get the HTML DOM element that will contain your map 
        // We are using a div with id="map" seen below in the <body>
        var mapElement = document.getElementById('googleMap');

        // Create the Google Map using our element and options defined above
        var map = new google.maps.Map(mapElement, mapOptions);

        // Let's also add a marker while we're at it
        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(23.7286, 90.3854),
            map: map,
            title: 'Tasfiu!',
            icon: 'images/icons/map.png',
            animation:google.maps.Animation.BOUNCE

        });
    }
</script>
{% endblock extra_scripts %}
   